=== lepouletsuisse/Christophe-Samuel/SER/Labo1/Cinema.dtd
<!ELEMENT cinema (projection*)>
        <!ELEMENT projection (date, numeroSalle, film, acteur*)>
        <!ELEMENT date (#PCDATA)>
        <!ELEMENT numeroSalle (#PCDATA)>
        <!ELEMENT film (titre, synopsis, duree, critiques*, genres*, motCle*, langages*, image, role*)>
        <!ELEMENT titre (#PCDATA)>
        <!ELEMENT synopsis (#PCDATA)>
        <!ELEMENT duree (#PCDATA)>
        <!ELEMENT critiques (texte, note)>
        <!ELEMENT texte (#PCDATA)>
        <!ELEMENT note (#PCDATA)>
        <!ELEMENT genres (#PCDATA)>
        <!ELEMENT motCle (#PCDATA)>
        <!ELEMENT langages (#PCDATA)>
        <!ELEMENT image (#PCDATA)>
        <!ELEMENT role (idActeur, nomRole, place)>
        <!ELEMENT idActeur (#PCDATA)>
        <!ELEMENT nomRole (#PCDATA)>
        <!ELEMENT place (#PCDATA)>
        <!ELEMENT acteur (nom, nomNaissance, biographie, sexe, dateNaissance, dateDeces)>
        <!ELEMENT nom (#PCDATA)>
        <!ELEMENT nomNaissance (#PCDATA)>
        <!ELEMENT biographie (#PCDATA)>
        <!ELEMENT sexe (#PCDATA)>
        <!ELEMENT dateNaissance (#PCDATA)>
        <!ELEMENT dateDeces (#PCDATA)>
        <!ATTLIST projection id CDATA #REQUIRED>
        <!ATTLIST film id CDATA #REQUIRED>
        <!ATTLIST acteur id CDATA #REQUIRED>

=== lepouletsuisse/Christophe-Samuel/SER/Labo1/Cinema.xml
<?xml version="1.0"?>
 <!DOCTYPE cinema SYSTEM "Cinema.dtd">
 <cinema>
 	<projection id="1">
         <date>10.02.2016</date>
         <numeroSalle>1</numeroSalle>
         <film id="1">
             <titre>One Punch Man</titre>
             <synopsis>Il arrive et tue tout le monde</synopsis>
             <duree>2:50</duree>
             <critiques>
                 <texte>Ce film est trop cooolllllll!! By JeanKevin</texte>
                 <note>11/10</note>
             </critiques>
             <genres>Action</genres>
             <genres>Aventure</genres>
             <motCle>Baston</motCle>
             <motCle>Punch</motCle>
             <langages>Francais</langages>
             <langages>Anglais</langages>
             <image>http://www.test.com</image>
             <role>
                 <idActeur>1</idActeur>
                 <nomRole>Man</nomRole>
                 <place>1</place>
             </role>
             <role>
                 <idActeur>2</idActeur>
                 <nomRole>Brigitte</nomRole>
                 <place>2</place>
             </role>
         </film>
         <acteur id="1">
             <nom>George Clooney</nom>
             <nomNaissance>Heidi</nomNaissance>
             <biographie>C'est un bon acteur, quoi que un peu vieux!</biographie>
             <sexe>Homme</sexe>
             <dateNaissance>20.03.1800</dateNaissance>
             <dateDeces></dateDeces>
         </acteur>
         <acteur id="2">
             <nom>Samantha Carter</nom>
             <nomNaissance>Sam</nomNaissance>
             <biographie>C'est une bonne actrice, quoi que un peu jeune!</biographie>
             <sexe>Femme</sexe>
             <dateNaissance>01.01.2015</dateNaissance>
             <dateDeces></dateDeces>
         </acteur>
     </projection>
	 <projection id="2">
         <date>10.02.2016</date>
         <numeroSalle>2</numeroSalle>
         <film id="2">
             <titre>Matrix</titre>
             <synopsis>A la fin, il meurt</synopsis>
             <duree>1:30</duree>
             <critiques>
                 <texte>Ce film est trop nulllllll!! By Billy</texte>
                 <note>0/10</note>
             </critiques>
             <genres>Action</genres>
             <genres>Romance</genres>
             <motCle>Love</motCle>
             <motCle>Amour</motCle>
             <langages>Francais</langages>
             <langages>Allemand</langages>
             <image>http://www.test2.com</image>
             <role>
                 <idActeur>3</idActeur>
                 <nomRole>Bob</nomRole>
                 <place>1</place>
             </role>
             <role>
                 <idActeur>4</idActeur>
                 <nomRole>Bill</nomRole>
                 <place>2</place>
             </role>
         </film>
         <acteur id="3">
             <nom>Brad Pitt</nom>
             <nomNaissance>Pitt</nomNaissance>
             <biographie>C'est un excellent acteur!</biographie>
             <sexe>Homme</sexe>
             <dateNaissance>20.03.1970</dateNaissance>
             <dateDeces></dateDeces>
         </acteur>
         <acteur id="4">
             <nom>Leonardo DiCaprio</nom>
             <nomNaissance>DiCaprio</nomNaissance>
             <biographie>C'est un tres mauvais acteur!</biographie>
             <sexe>Homme</sexe>
             <dateNaissance>01.01.1979</dateNaissance>
             <dateDeces></dateDeces>
         </acteur>
     </projection>
 </cinema>
